### ISSUE TITLE
Index Out of Range?

### ISSUE THREAD

**Issue by ChibiRere** [RainThunder/Fire-Emblem-Fates-Convoy-Editor#3]
Before I begin, I must confess that I 'm a total NOOB when it comes to programming. I'm having an issue when I try to use the Convoy Editor on my Awakening save file. The error message states that the index was out of range, and must be non-negative and less that the size of the collection. The detailed explanation is as follows:

**_See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at Fire_Emblem_Fates_Convoy_Editor.ConvoyEditor.loadItems()
   at Fire_Emblem_Fates_Convoy_Editor.ConvoyEditor.loadSave(String filepath)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Fire Emblem Fates Convoy Editor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Chibi/Desktop/Fire%20Emblem%20Awakening%20Convoy%20Editor/Fire.Emblem.Fates.Convoy.Editor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box._**

Am I missing something totally obvious or do I need to use a different program to extract my saves?

Thanks a million!

**Comment by ghost** [comment]
Same for me

**Comment by hebroin** [comment]
It does the same thing for me if I use the latest release.
Downloaded the source zip, opened it in VS2017 to see what the problem is and it worked!?

I managed to edit the convoy with a compress save, import the save back and the convoy was modify in-game.

**Comment by Xedict** [comment]
~~Wait, so what do I need to do to make editing Awakening save files work? I can't open them.~~

Nevermind, I found what you did. Works perfectly!

**Comment by xSASxZaros** [comment]
Mine does the same thing - I used SaveDataFiler to backup the save - Anyone know why it's coming up with the index error? Do I need to do anything else to use the save before I can edit it? (Awakening save).

Regards.

**Comment by hebroin** [comment]
I guess there is a bug in the release version, but the source is up to date. Might be a problem of permission with the executable.

I'll give it a closer look but in the mean time, you can download the source and execute the program from visual studio directly.

**Comment by xSASxZaros** [comment]
Oh never mind, I managed to work it out. I seemed to have got it to work now. :)

Regards.

**Comment by megamaster88** [comment]
I tried loading the newest source code into VS2017 but whenever I try to load up a save it gives me the same error just in VS 2017. How was anybody able to run it via VS2017?
![capture](https://user-images.githubusercontent.com/30580032/28757950-bf2f0606-7542-11e7-8bd6-ad8f4d565e79.PNG)

**Comment by hebroin** [comment]
Can you share your save? We'll see if it does it for me too.

**Comment by megamaster88** [comment]
It won't let me send the file normally so I had to put it in a zip file
[Chapter2.zip](https://github.com/RainThunder/Fire-Emblem-3DS-Convoy-Editor/files/1186155/Chapter2.zip)

**Comment by hebroin** [comment]
It's weird because it is working for me. I edited the number of Seed of Trust if you want to load it back to see if it worked.

[EDIT] I can't find the method that breaks in the code. Are you sure you have the latest version? Here's a zip of the source I got from the repo.
[Fire-Emblem-3DS-Convoy-Editor-master.zip](https://github.com/RainThunder/Fire-Emblem-3DS-Convoy-Editor/files/1186172/Fire-Emblem-3DS-Convoy-Editor-master.zip)


[Chapter2.zip](https://github.com/RainThunder/Fire-Emblem-3DS-Convoy-Editor/files/1186168/Chapter2.zip)

**Comment by megamaster88** [comment]
Oh ok so then either I'm doing something wrong or my computer is acting stupid XD How did you get it to work without it giving you an error?

**Comment by megamaster88** [comment]
Ok, so the new version of the convoy editor you gave me works I don't know why the other versions didn't because I got the newest release of the source but oh well thanks for the help! :)

**Comment by hebroin** [comment]
The source I gave you is from the master branch directly, not from the v1.1 release, that's why.

If @RainThunder could just put another release up it would fix the problem.
